import { stemmer } from "stemmer";
import type { TermVector } from "@lectern/shared";

/**
 * Text -> normalized term tokens. The SAME tokenizer is used for the seed
 * corpus AND for candidate articles, so profile terms and candidate terms live
 * in the same stemmed vocabulary (a prerequisite for meaningful TF-IDF cosine).
 *
 * Pipeline: lowercase -> strip non-alpha -> drop stopwords -> Porter stem.
 * Stopwords are matched BEFORE stemming (they are ordinary English words).
 */

// ~150 common English stopwords. Kept inline (no runtime dependency) so the
// tokenizer is fully deterministic and self-contained.
const STOPWORDS = new Set<string>([
  "a",
  "about",
  "above",
  "after",
  "again",
  "against",
  "all",
  "am",
  "an",
  "and",
  "any",
  "are",
  "aren",
  "as",
  "at",
  "be",
  "because",
  "been",
  "before",
  "being",
  "below",
  "between",
  "both",
  "but",
  "by",
  "can",
  "cannot",
  "could",
  "couldn",
  "did",
  "didn",
  "do",
  "does",
  "doesn",
  "doing",
  "don",
  "down",
  "during",
  "each",
  "few",
  "for",
  "from",
  "further",
  "had",
  "hadn",
  "has",
  "hasn",
  "have",
  "haven",
  "having",
  "he",
  "her",
  "here",
  "hers",
  "herself",
  "him",
  "himself",
  "his",
  "how",
  "i",
  "if",
  "in",
  "into",
  "is",
  "isn",
  "it",
  "its",
  "itself",
  "just",
  "let",
  "me",
  "more",
  "most",
  "mustn",
  "my",
  "myself",
  "no",
  "nor",
  "not",
  "now",
  "of",
  "off",
  "on",
  "once",
  "only",
  "or",
  "other",
  "ought",
  "our",
  "ours",
  "ourselves",
  "out",
  "over",
  "own",
  "same",
  "shan",
  "she",
  "should",
  "shouldn",
  "so",
  "some",
  "such",
  "than",
  "that",
  "the",
  "their",
  "theirs",
  "them",
  "themselves",
  "then",
  "there",
  "these",
  "they",
  "this",
  "those",
  "through",
  "to",
  "too",
  "under",
  "until",
  "up",
  "very",
  "was",
  "wasn",
  "we",
  "were",
  "weren",
  "what",
  "when",
  "where",
  "which",
  "while",
  "who",
  "whom",
  "why",
  "will",
  "with",
  "won",
  "would",
  "wouldn",
  "you",
  "your",
  "yours",
  "yourself",
  "yourselves",
  "s",
  "t",
  "re",
  "ve",
  "ll",
  "d",
  "m",
  "o",
  "y",
  "also",
  "get",
  "got",
  "one",
  "two",
  "may",
  // --- Publication / newsletter / web-chrome boilerplate ---
  // These dominate raw body text (mastheads, "in this issue", nav, footers) and
  // otherwise swamp the interest profile with no-signal terms, so a candidate
  // scores high just for containing "issue" or "read more". Matched pre-stem.
  "issue",
  "issues",
  "vol",
  "volume",
  "edition",
  "editions",
  "newsletter",
  "subscribe",
  "subscriber",
  "subscription",
  "unsubscribe",
  "archive",
  "archives",
  "digest",
  "weekly",
  "daily",
  "monthly",
  "roundup",
  "briefing",
  "dispatch",
  "home",
  "page",
  "pages",
  "click",
  "read",
  "reads",
  "comment",
  "comments",
  "share",
  "sign",
  "email",
  "follow",
  "menu",
  "login",
  "register",
  "account",
  "contact",
  "privacy",
  "terms",
  "copyright",
  "rights",
  "reserved",
  "cookie",
  "cookies",
  "today",
  "yesterday",
  "tomorrow",
  "week",
  "weeks",
  "month",
  "months",
  "year",
  "years",
  "day",
  "days",
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
  "january",
  "february",
  "march",
  "april",
  "june",
  "july",
  "august",
  "september",
  "october",
  "november",
  "december",
  "new",
  "news",
  "post",
  "posts",
  "update",
  "updates",
  "latest",
  "top",
  "best",
  "via",
  "link",
  "links",
  "blog",
  "blogs",
  "site",
  "website",
  "www",
  "com",
  "http",
  "https",
  "url",
  "us",
  "use",
  "used",
  "using",
  "like",
  "make",
  "makes",
  "made",
  "thing",
  "things",
  "way",
  "ways",
  "people",
  "time",
  "times",
  "first",
  "last",
  "next",
  "back",
  "said",
  "says",
  "say",
  "want",
  "need",
  "know",
  "think",
  "see",
  "look",
  "going",
  "really",
  "much",
  "many",
  "lot",
  "good",
  "great",
]);

/** Lowercase, strip non-alpha, drop stopwords, Porter-stem. Deterministic. */
export function tokenize(text: string): string[] {
  if (!text) return [];
  return (
    text
      .toLowerCase()
      // Replace every non a-z run with a single space so contractions/punctuation
      // split cleanly (e.g. "don't" -> "don" "t", both stopwords).
      .replace(/[^a-z]+/g, " ")
      .split(" ")
      .filter((w) => w.length > 1 && !STOPWORDS.has(w))
      .map((w) => stemmer(w))
  );
}

/**
 * Map each Porter stem to the FIRST surface form (original lowercased word) that
 * produced it in `text`. The scorer works in stems ("connect", "intellig"),
 * which are ugly to show a user — this lets the "why this?" terms render the
 * readable word ("connection", "intelligence") the reader actually saw. Uses the
 * same lowercase → strip-non-alpha → stopword pipeline as `tokenize` (minus the
 * stemming) so surface words and their stems line up exactly.
 */
export function surfaceForms(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  if (!text) return out;
  for (const word of text
    .toLowerCase()
    .replace(/[^a-z]+/g, " ")
    .split(" ")) {
    if (word.length <= 1 || STOPWORDS.has(word)) continue;
    const stem = stemmer(word);
    if (!(stem in out)) out[stem] = word;
  }
  return out;
}

/**
 * Fold a token list into a sparse term-frequency vector. `weight` scales each
 * occurrence (used to fold a seed doc's weight into its term counts).
 */
export function termFrequencies(tokens: string[], weight = 1): TermVector {
  const tf: TermVector = {};
  for (const token of tokens) {
    tf[token] = (tf[token] ?? 0) + weight;
  }
  return tf;
}
