#!/bin/bash

source /usr/share/yunohost/helpers

if yunohost service status "$app" >/dev/null 2>&1; then
    yunohost service remove "$app"
fi

ynh_config_remove_systemd
ynh_config_remove_nginx
ynh_safe_rm "/var/log/$app"

# The postgres DB, install_dir, data_dir, system user, port and nodejs version
# are deprovisioned automatically by their manifest resources.
